
import Models.Tarea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pablo
 */
// Req (4;1) Implementar un diálogo personalizado utilizando JDialog Form
public class VistaNuevaTarea extends javax.swing.JDialog { // Cambiado de JFrame a JDialog

    private Tarea tareaCreada = null; // Variable para almacenar el resultado

    // Req (4;1) Constructor para JDialog 
    public VistaNuevaTarea(java.awt.Frame parent, boolean modal) {
        super(parent, modal); // Esto es lo que quita el error
        initComponents();
        this.setLocationRelativeTo(null);
        PaintPanel miPanelDibujo = new PaintPanel();
miPanelDibujo.setPreferredSize(new java.awt.Dimension(200, 100));
datos_input.add(miPanelDibujo); // Lo añadimos al contenedor de tus inputs
    }
    
    // Req (4;2) Método para devolver el valor a la ventana que lo invoca
    public Tarea getTareaCreada() {
        return tareaCreada;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        datos_input = new javax.swing.JPanel();
        jPanel_descripcion = new javax.swing.JPanel();
        label_descripcion = new javax.swing.JLabel();
        input_descripcion = new javax.swing.JTextField();
        jPanel_prioridad = new javax.swing.JPanel();
        label_prioridad = new javax.swing.JLabel();
        input_prioridad = new javax.swing.JTextField();
        jPanel_categoria = new javax.swing.JPanel();
        label_categoria = new javax.swing.JLabel();
        input_categoria = new javax.swing.JTextField();

        setTitle("Añadir tarea");
        setPreferredSize(new java.awt.Dimension(450, 500));

        jButton1.setText("Guardar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(77, 28));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        datos_input.setLayout(new java.awt.GridLayout(4, 0));

        jPanel_descripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel_descripcion.setLayout(new java.awt.BorderLayout());

        label_descripcion.setText("Descripción");
        label_descripcion.setToolTipText("");
        jPanel_descripcion.add(label_descripcion, java.awt.BorderLayout.NORTH);

        input_descripcion.setMinimumSize(new java.awt.Dimension(2147483647, 28));
        input_descripcion.setPreferredSize(new java.awt.Dimension(2147483647, 28));
        input_descripcion.setRequestFocusEnabled(false);
        jPanel_descripcion.add(input_descripcion, java.awt.BorderLayout.SOUTH);

        datos_input.add(jPanel_descripcion);

        jPanel_prioridad.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel_prioridad.setLayout(new java.awt.BorderLayout());

        label_prioridad.setText("Prioridad");
        label_prioridad.setToolTipText("");
        jPanel_prioridad.add(label_prioridad, java.awt.BorderLayout.NORTH);

        input_prioridad.setMinimumSize(new java.awt.Dimension(2147483647, 28));
        input_prioridad.setPreferredSize(new java.awt.Dimension(2147483647, 28));
        input_prioridad.setRequestFocusEnabled(false);
        jPanel_prioridad.add(input_prioridad, java.awt.BorderLayout.SOUTH);

        datos_input.add(jPanel_prioridad);

        jPanel_categoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel_categoria.setLayout(new java.awt.BorderLayout());

        label_categoria.setText("Categoria");
        label_categoria.setToolTipText("");
        jPanel_categoria.add(label_categoria, java.awt.BorderLayout.NORTH);

        input_categoria.setMinimumSize(new java.awt.Dimension(2147483647, 28));
        input_categoria.setPreferredSize(new java.awt.Dimension(2147483647, 28));
        input_categoria.setRequestFocusEnabled(false);
        jPanel_categoria.add(input_categoria, java.awt.BorderLayout.SOUTH);

        datos_input.add(jPanel_categoria);

        getContentPane().add(datos_input, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String desc = input_descripcion.getText().trim();
        String prio = input_prioridad.getText().trim();
        String cat = input_categoria.getText().trim();
        
        if (!desc.isEmpty()) {
            // Creamos el objeto con tus datos (Req 2;6.b)
            Tarea nuevaTarea = new Tarea(desc, prio, cat, "Sin notas adicionales");
                        
            // Añadimos al modelo estático de la principal
            VistaPrincipal.modeloGlobalTareas.addElement(nuevaTarea);
            
            // Cerramos esta ventana
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Escribe al menos una descripción");
        }        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel datos_input;
    private javax.swing.JTextField input_categoria;
    private javax.swing.JTextField input_descripcion;
    private javax.swing.JTextField input_prioridad;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel_categoria;
    private javax.swing.JPanel jPanel_descripcion;
    private javax.swing.JPanel jPanel_prioridad;
    private javax.swing.JLabel label_categoria;
    private javax.swing.JLabel label_descripcion;
    private javax.swing.JLabel label_prioridad;
    // End of variables declaration//GEN-END:variables
}
