
import Models.Tarea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pablo
 */
public class VistaDetalleTarea extends javax.swing.JFrame {
    
    private Tarea tarea;

    /**
     * Creates new form VistaDetalleTarea
     */
    public VistaDetalleTarea(Tarea tarea) {
        initComponents();
        setTarea(tarea); // Usamos el mismo método de actualización
    }
    
    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
        actualizarInterfaz(); // Aquí llenas tus JTextFields/JLabels con los datos de la tarea
    }
    
    private void actualizarInterfaz() {
        titulo_tarea.setText(tarea.getDescripcion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo_tarea = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        titulo_tarea.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        titulo_tarea.setText("Titulo");
        titulo_tarea.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.add(titulo_tarea);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jSeparator1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(450, 500));
        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel titulo_tarea;
    // End of variables declaration//GEN-END:variables
}
